alias rmd='rm -rf'
alias py='python3'
alias pip='pip3'
alias la='ls -lA --color=auto'
alias untar='tar -zxvf'
alias wget='wget -c'
alias f='fzf'
alias install='sudo apt-get install'
alias upgrade='sudo apt-get upgrade'
alias update='sudo apt-get update'
alias www='py -m http.server'
alias pwww='php -S 127.0.0.1:8000'
alias ga='git add *'
alias gc='git commit -m'
alias gpush='git push origin main'
alias gpull='git pull origin main'
alias ..='cd ..'
alias ...='cd  ../..'
alias ....='cd ../../..'
alias dev='source venv/bin/activate'
alias pipupg='pip install --upgrade pip'
alias pipupd='pip freeze --user | cut -d'=' -f1 | xargs -n1 pip install -U'
alias pipfreeze='pip freeze > requirements.txt'
alias pipinstall='pip install -r requirements.txt'
alias pi='ssh pi@192.168.1.102'
alias jup="jupyter-notebook --allow-root"